### ISSUE TITLE
Running "python /srv/main.py" issue

### ISSUE THREAD

**Issue by averyct** [colinodell/mqtt-control-panel#5]
Once I run 'python /srv/main.py', I get this error:

`Traceback (most recent call last):
File "/srv/main.py", line 21, in <module>
PINS = os.environ.get('PINS').split(',')
AttributeError: 'NoneType' object has no attribute 'split'`

What should I do to get this to work? I'm decently knowledgeable with Raspberry Pi, but not good enough to code or edit code :/ Thanks!

**Comment by colinodell** [comment]
Make sure you have [copied the `.env` file](https://github.com/colinodell/mqtt-control-panel#configuration) and that it contains `PINS=` plus some value.
